version: "2"
run:
  timeout: 5m

linters:
  exclusions:
    paths:
      - internal
      - pkg/registry
    rules:
      - path: test
        linters:
          - gosec
  enable:
    - asciicheck
    - depguard
    - errorlint
    - gosec
    - importas
    - misspell
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: crypto/sha256
              desc: use crypto.SHA256 instead
formatters:
  exclusions:
    paths:
      - internal
      - pkg/registry
  enable:
    - gofmt
    - goimports
